
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;
import java.lang.Integer;


/**
 *
 * @author hena
 */
public class QuesDisplay extends javax.swing.JFrame {
int round;
String qid;
    
    public QuesDisplay(int r) {
        this.round=r;
        initComponents();
        ImageIcon icon = new ImageIcon(this.getClass().getResource("coding1.jpeg"));
        this.setIconImage(icon.getImage());
        this.getContentPane().setBackground(Color.DARK_GRAY);
        this.setTitle("CODEON");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quesList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        submitCode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quesList.setFont(new java.awt.Font("TlwgTypewriter", 1, 14)); // NOI18N
        quesList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Select--", "A", "B", "C", "D", "E", "F" }));
        quesList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quesListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("TlwgTypewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(23, 28, 226));
        jLabel1.setText("QUESTION :");

        submitCode.setFont(new java.awt.Font("TlwgTypewriter", 1, 14)); // NOI18N
        submitCode.setForeground(new java.awt.Color(36, 24, 226));
        submitCode.setText("SUBMIT");
        submitCode.setToolTipText("Redirect to submission page");
        submitCode.setMaximumSize(new java.awt.Dimension(156, 33));
        submitCode.setMinimumSize(new java.awt.Dimension(156, 33));
        submitCode.setPreferredSize(new java.awt.Dimension(156, 33));
        submitCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCodeActionPerformed(evt);
            }
        });

        question.setColumns(20);
        question.setForeground(new java.awt.Color(38, 110, 24));
        question.setRows(5);
        jScrollPane1.setViewportView(question);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1450433422_Back.png"))); // NOI18N
        jButton1.setToolTipText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1450433401_Delete.png"))); // NOI18N
        close.setToolTipText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(quesList, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(submitCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quesList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(submitCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCodeActionPerformed
        qid=(String)quesList.getSelectedItem();
        JudgePlatform j=new JudgePlatform(round,qid);
        this.hide();
        j.show();
    }//GEN-LAST:event_submitCodeActionPerformed

    private void quesListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quesListActionPerformed
        String t=null;
        try{
        if(quesList.getSelectedIndex()==1)//problem A
        {
           t=readfile(""+round+"/"+"A/ques.txt");
           question.setText(t);
        }
        else
        if(quesList.getSelectedIndex()==2)//problem B
        {
           t=readfile(""+round+"/"+"B/ques.txt");
           question.setText(t);
        }
        else
        if(quesList.getSelectedIndex()==3)//problem C
        {
           t=readfile(""+round+"/"+"C/ques.txt");
           question.setText(t);
        }
         else
        if(quesList.getSelectedIndex()==4)//problem D
        {
           t=readfile(""+round+"/"+"D/ques.txt");
           question.setText(t);
        }
         else
        if(quesList.getSelectedIndex()==5)//problem E
        {
           t=readfile(""+round+"/"+"E/ques.txt");
           question.setText(t);
        }
         else
        if(quesList.getSelectedIndex()==6)//problem F
        {
           t=readfile(""+round+"/"+"F/ques.txt");
           question.setText(t);
        }
        }
        catch(IOException e)
        {}
                
    }//GEN-LAST:event_quesListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FetchCases f=new FetchCases();
        this.hide();
        f.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed
String readfile(String filename) throws IOException
{
    BufferedReader br=new BufferedReader(new FileReader(filename));
    try{
        StringBuilder sb=new StringBuilder();
        String line=br.readLine();
        while(line!=null){
            sb.append(line);
            sb.append("\n");
            line=br.readLine();
        }
        return sb.toString();
    }
    finally{
        br.close();
                
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuesDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new QuesDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox quesList;
    private javax.swing.JTextArea question;
    private javax.swing.JButton submitCode;
    // End of variables declaration//GEN-END:variables
}
